"""empty message

Revision ID: b2a479e69d35
Revises: ce9aacd4d1df
Create Date: 2021-01-20 22:28:03.325288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a479e69d35'
down_revision = 'ce9aacd4d1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_item', sa.Column('completed', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_item', 'completed')
    # ### end Alembic commands ###
